# Generated by Django 5.2.10 on 2026-04-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_category_categories__user_id_15497c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Acumulado')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('color', models.CharField(choices=[('#22c55e', 'Verde'), ('#3b82f6', 'Azul'), ('#a855f7', 'Roxo'), ('#f97316', 'Laranja'), ('#eab308', 'Amarelo'), ('#ef4444', 'Vermelho'), ('#ec4899', 'Rosa'), ('#14b8a6', 'Turquesa')], default='#22c55e', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='categories.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['deadline', 'name'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='goals_goal_user_id_c14f76_idx'), models.Index(fields=['user', 'deadline'], name='goals_goal_user_id_38b5f2_idx')],
            },
        ),
    ]
