# Generated by Django 5.2.10 on 2026-02-13 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx'),
        ),
    ]
