# Generated by Django 5.2.10 on 2026-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_accounts_ac_user_id_0bca0f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('nubank', 'Nubank'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('santander', 'Santander'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa'), ('inter', 'Inter'), ('c6', 'C6 Bank'), ('other', 'Outro')], max_length=20, null=True, verbose_name='Código do Banco'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Conta Padrão'),
        ),
    ]
