# Generated by Django 5.2.10 on 2026-04-24 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_bank_code_account_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bank_code', models.CharField(choices=[('nubank', 'Nubank'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('santander', 'Santander'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa'), ('inter', 'Inter'), ('c6', 'C6 Bank'), ('other', 'Outro')], max_length=20, verbose_name='Código do Banco')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite de Crédito')),
                ('closing_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de Vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('color', models.CharField(default='#22c55e', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(verbose_name='Mês de Referência')),
                ('closing_date', models.DateField(verbose_name='Data de Fechamento')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('paid', 'Paga')], default='open', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_card_bills', to='accounts.account', verbose_name='Conta de Pagamento')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.creditcard', verbose_name='Cartão de Crédito')),
            ],
            options={
                'verbose_name': 'Fatura do Cartão',
                'verbose_name_plural': 'Faturas do Cartão',
                'ordering': ['-reference_month'],
                'unique_together': {('credit_card', 'reference_month')},
            },
        ),
    ]
