# Generated by Django 5.2.10 on 2026-04-24 22:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_bank_code_account_is_default'),
        ('categories', '0003_category_categories__user_id_15497c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo de Transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('day_of_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia do Mês')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='Último Lançamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='accounts.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='categories.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['transaction_type', 'day_of_month', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='recurrences_user_id_f8aa53_idx'), models.Index(fields=['user', 'transaction_type'], name='recurrences_user_id_1c7728_idx')],
            },
        ),
    ]
