# Generated by Django 5.2.10 on 2026-02-13 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Descrição'),
        ),
    ]
