# Generated by Django 5.2.10 on 2026-02-13 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_accounts_ac_user_id_0bca0f_idx'),
        ('categories', '0003_category_categories__user_id_15497c_idx_and_more'),
        ('transactions', '0002_alter_transaction_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_98a6b3_idx'),
        ),
    ]
