# Generated by Django 5.2.10 on 2026-04-24 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_creditcard_cardbill'),
        ('transactions', '0003_transaction_transaction_user_id_8af7f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.creditcard', verbose_name='Cartão de Crédito'),
        ),
    ]
