# Generated by Django 5.2.10 on 2026-02-13 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_category_type_alter_category_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_active'], name='categories__user_id_15497c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_default', 'is_active'], name='categories__is_defa_cb891d_idx'),
        ),
    ]
