# Generated by Django 5.2.10 on 2026-04-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='análise completa')),
                ('summary', models.CharField(max_length=500, verbose_name='resumo')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='tokens utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
